key: Z1zHqK4rtUYIdJvJNdTTRPLa5Ntp5h0uAFBUWDoipFUdLFFE1OzfwboIXUQNLBhmckLPrywXscb0xzawb5Otw0qFy3fl+tw7TeW0BZhTpMv/s/buEcW6D+JoLNNd+yE+03B7Qy/5GEsG2ckwr5qasaP5NER35+FkIr5W+nD10ZdwrHZEyanZpD9D/ZdDocJ2ht9kFYKxd/Wh+ul65ZYFIcSwrP8mJfdrhNB6fPx37WiNxHqV7oHyHcyRLCPYlro570cUY+FHuHlEp2TxsDEiEe8iLnO4rc17szjmOxvSBfgxKiFBIZUoyGNI7rEQdp/7qhRnbebNUK6zzpKGci2vNLDTAVSScB4aqhl0AFDkXrzs3SFHvoDMvGguLcd+k53Z2DK2MoZwmNBY9DmPIki+b0PgOm4dxx5nH48Lw55qAy6LL4NRbeV/5X4/SQYNyaXP/nXfMo3jDWbjx2FlVBd1FYI8xT+cVIOu3GmeWIisAej5ba4tZCKh9IpD+2Sy5VyneyZkXTEgSA8gBM9zGoy08j0RwdbbdnJ6vzHI/U0u4huuhDctsqTXrRJ9QDdlHLstYtdxOgUfDI1IjUFWeo0dD2uWjz+Vm9VvuFFymySfFg59ZiyLfIbyimWI89bXUw/uir8EwQp7R7j7CNKXdWL/RA==
metrics:
  plugins:
    - name: jvmjolokia
      enabled: true
      interval: 300
      config:
        ip: 172.31.255.142
        password: admin
        protocol: http
        username: admin
        port: 8778
        context: jolokia
        monitorDeadlocks: false
        deadLockMonitoringInterval: 300
